README.md
=> Update links to docs and medium posts

src/Domain/Command/MySqlExportTableCommand.php, src/Domain/DataMigration/EntityTableNameFetcher.php, src/Domain/DataMigration/TableMigrator.php
This PR prevents the tool to produce files in the source PIM and use /tmp instead.
=> MIG-59: Do not touch or produce something in the pim source

src/Infrastructure/Common/config/services.yml
[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)
it migrates EE system data (some permissions):
tables migrated:
'pimee_security_attribute_group_access'
'pimee_security_product_category_access'
'pimee_security_locale_access'
[//]: <> (What does this Pull Request do? reference the related issue?)
=> MIG-3: Migrate EE system data

.github/CONTRIBUTING.md
[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)
This PR introduces a technical documentation. 
[//]: <> (What does this Pull Request do? reference the related issue?)
=> Doc: Add a little bit of dev documentation

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, src/Infrastructure/Common/config/services.yml
This PR migrates the table : pimee_security_job_profile_access
=> MIG-7: Add job permission table

CHANGELOG.md, README.md, UPGRADE-2.0.md
This follow this PR https://github.com/akeneo/transporteo/pull/58 adapting the Upgrade file with the Transporteo usage.
We do not support docker, pim installed locally...
=> Update the readme

src/Infrastructure/Common/ContainerBuilder.php, src/Infrastructure/Common/config/parameters.yml, src/Infrastructure/MigrationStep/S010FromReadyToSourcePimConfigured.php, src/Infrastructure/MigrationStep/S015FromSourcePimConfiguredToSourcePimApiConfigured.php, src/Infrastructure/MigrationStep/S040FromSourcePimDetectedToDestinationPimDownloaded.php, src/Infrastructure/MigrationStep/S050FromDestinationPimDownloadedToDestinationPimInstalled.php, src/Infrastructure/TransporteoStateMachine.php, src/Infrastructure/UserInterface/Cli/Transporteo.php, tests/spec/Infrastructure/MigrationStep/S010FromReadyToSourcePimConfiguredSpec.php, tests/spec/Infrastructure/MigrationStep/S015FromSourcePimConfiguredToSourcePimApiConfiguredSpec.php, tests/spec/Infrastructure/MigrationStep/S040FromSourcePimDetectedToDestinationPimDownloadedSpec.php, tests/spec/Infrastructure/MigrationStep/S050FromDestinationPimDownloadedToDestinationPimInstalledSpec.php
Add possibility to define default responses in a yaml parameters config file. 
Quick and dirty for the hackathon. We should think to a better way to do that later.
=> Add possibility to define defaults responses

CHANGELOG.md, README.md
=> Add scope details in documentation

CHANGELOG.md, src/Infrastructure/Cli/AbstractConsole.php, src/Infrastructure/Cli/SshConsole.php
Changes to handle empty values in MySQL connection string consruction
=> ISSUE-78: Add support for null as database password

src/Infrastructure/Cli/LocalConsole.php, src/Infrastructure/Cli/SshConsole.php
Fix a missing log for executing an ApiCommand in SshConsole
Improve the logs for have the full command string.
=> Improve logs of commands execution

src/Domain/Pim/DestinationPim.php
=> GITHUB-93: Fix destination pim version check

src/Domain/Pim/AbstractPim.php, src/Domain/Pim/DestinationPim.php, src/Domain/Pim/Pim.php, src/Domain/Pim/SourcePim.php, tests/integration/Domain/SourcePimDetection/SourcePimDetectorIntegration.php, tests/spec/Domain/Pim/DestinationPimSpec.php, tests/spec/Domain/Pim/SourcePimSpec.php, tests/spec/Infrastructure/MigrationStep/S020FromSourcePimApiConfiguredToSourcePimDetectedSpec.php
| Review and 2 GTM                  | Ok
| Micro Demo to the PO (Story only) | Ok
=> MIG-65: Remove useless method who throw exception when trying to migrate PIM 1.7 with IVB

src/Infrastructure/Cli/SshConsole.php
=> GITHUB-95: Fix SshConsole constructor

Makefile, src/Domain/PrinterAndAsker.php, src/Infrastructure/Cli/SshConsole.php, src/Infrastructure/Common/messages.en.yml, src/Infrastructure/MigrationStep/S010FromReadyToSourcePimConfigured.php, src/Infrastructure/Pim/SshConnection.php, src/Infrastructure/SshFileFetcher.php, src/Infrastructure/UserInterface/Cli/ConsolePrinterAndAsker.php, tests/spec/Infrastructure/MigrationStep/S010FromReadyToSourcePimConfiguredSpec.php
=> MIG-71: Add Ssh with passphrase support

src/Domain/Command/JobExecutionCommand.php, src/Domain/Command/SymfonyCommand.php, src/Domain/DataMigration/EntityMappingChecker.php, src/Domain/DataMigration/EntityTableNameFetcher.php, src/Domain/MigrationStep/s050_DestinationPimInstallation/DestinationPimSystemRequirementsChecker.php, src/Domain/MigrationStep/s150_ProductVariationMigration/FamilyVariantImporter.php, src/Domain/MigrationStep/s150_ProductVariationMigration/InnerVariationTypeMigrator.php, src/Domain/MigrationStep/s150_ProductVariationMigration/ProductModelImporter.php, src/Infrastructure/Cli/AbstractConsole.php, src/Infrastructure/DestinationPimInstallation/BasicDestinationPimSystemRequirementsInstaller.php, tests/spec/Domain/DataMigration/EntityMappingCheckerSpec.php, tests/spec/Domain/MigrationStep/s150_ProductVariationMigration/InnerVariationTypeMigratorSpec.php
| Added Specs                       | Ok
| Review and 2 GTM                  | Ok
| Micro Demo to the PO (Story only) | -
=> MIG-75: Add env to symfony command class

src/Domain/FileSystemHelper.php, src/Infrastructure/Common/ContainerBuilder.php, src/Infrastructure/UserInterface/Cli/Transporteo.php
=> MIG-68: Clean var directory before start migration

README.md
add "image and asset files" for community and enterprise as WIP
=> Update data migration status

README.md
set asset and images files as not in WIP.
=> Update readme for assets and images files

README.md
Wrong links, should redirect to new doc: https://docs.akeneo.com/2.0/install_pim/manual/system_requirements/system_requirements.html
=> Update System requirements links

README.md, doc/advance-usage.md, doc/product-variants-migration.md, doc/requirements.md, src/Infrastructure/Common/config/parameters.yml
I hesitate to put the scope in a specific file, but I think that it's better to have it directly in the changelog
=> Add some documentation
